# Aqui se pueden activar o desactivar las reglas de estilo y sintaxis
# recomendadas para aplicaciones Flutter, mostradas en Dart Analysis.
# Lista completa y documentación de cada regla (lint):
# https://dart-lang.github.io/linter/lints/index.html
include: package:flutter_lints/flutter.yaml

linter:
  rules:
    # Ignora la recomendacion de no incluir prints en código de produccion.
    avoid_print: false
    # Para separar visualmente los imports locales de los paquetes externos.
    prefer_relative_imports: true

