# Configuracion de parametros para json_serializable. Para mas informacion:
# https://pub.dev/packages/json_serializable#build-configuration
# Nota: AndroidStudio muestra un warining: 'targets is not allowed' que se puede ignorar.
targets:
  $default:
    builders:
      json_serializable:
        options:
          checked: true
          create_to_json: false
          disallow_unrecognized_keys: true
