# Configuracion de parametros para json_serializable. Mas info:
# https://github.com/google/json_serializable.dart/tree/master/json_serializable#build-configuration
# AndroidStudio muestra un warining: 'targets is not allowed' que se puede ignorar.
targets:
  $default:
    builders:
      json_serializable:
        options:
          checked: true
          create_to_json: false
          disallow_unrecognized_keys: true
