name: tablero_cst
description: Tablero de Información sobre los servicios de la Coordinacion de Servicios Tecnológicos de CIMAT

publish_to: 'none'

version: 0.2.0

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter_vector_icons: ^1.0.0
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  json_annotation: ^4.0.1
  provider: ^5.0.0

dev_dependencies:
  build_runner: ^2.0.4
  intl: ^0.17.0
  json_serializable: ^4.1.3
  effective_dart: ^1.3.1

flutter:
  uses-material-design: true

  assets:
    - datos/datos_sgp_desarrollo_v2.json
    - imagenes/
