name: tablero_cst
description: Tablero de información de la Coordinacion de Servicios Tecnológicos de CIMAT

publish_to: 'none'

version: 1.0.0

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  flutter_vector_icons: ^1.0.0
  json_annotation: ^4.0.1
  provider: ^6.0.0
  charts_flutter: ^0.11.0

dev_dependencies:
  build_runner: ^2.1.2
  intl: ^0.17.0
  json_serializable: ^4.1.4
  flutter_lints: ^1.0.4

flutter:
  uses-material-design: true

  assets:
    - datos/
    - imagenes/
