name: tablero_cst
description: Tablero de Información sobre los servicios de la Coordinacion de Servicios Tecnológicos de CIMAT

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 0.1.0

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  json_annotation: ^4.0.1

dev_dependencies:
  effective_dart: ^1.3.1
  build_runner: ^2.0.3
  json_serializable: ^4.1.1

flutter:
  uses-material-design: true

  assets:
    - assets/datos/
    - assets/imagenes/
